CarRental/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRental.Data;
using CarRental.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarRental.Controllers
{
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
              return _context.Car != null ? 
                          View(await _context.Car.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Car'  is null.");
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Manufacturer,Model,Year,Color,RentalPricePerDay")] Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Manufacturer,Model,Year,Color,RentalPricePerDay")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Car == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Car == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Car'  is null.");
            }
            var car = await _context.Car.FindAsync(id);
            if (car != null)
            {
                _context.Car.Remove(car);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
          return (_context.Car?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpPost]
        public IActionResult Rent(int carId, DateTime pickupDate, DateTime returnDate)
        {
            var clientId = (int)TempData["ClientId"];
            var client = _context.Clients.Find(clientId);
            var car = _context.Cars.Find(carId);

            if (car == null)
            {
                return NotFound();
            }

            if (client == null)
            {
                return NotFound();
            }

            if (pickupDate == default || returnDate == default)
            {
                return BadRequest("Pickup and return dates are required.");
            }

            decimal rentalPricePerDay = Convert.ToDecimal(car.RentalPricePerDay);
            int timePeriod = (int)(returnDate - pickupDate).TotalDays;
            var rental = new Rental
            {
                ClientId = clientId,
                CarId = carId,
                PickupDate = pickupDate,
                ReturnDate = returnDate,
                TotalPrice = rentalPricePerDay * timePeriod,
                CarManufacturer = car.Manufacturer,
                CarModel = car.Model,
                ClientUsername = client.Username
            };
            _context.Rentals.Add(rental);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

CarRental/Controllers/HomeController.cs
using CarRental.Data;
using CarRental.Models;
using CarRental.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarRental.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _dbContext;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registration(RegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var client = new Client
                {
                    // Map properties from RegistrationViewModel to Client
                    Username = model.Username,
                    Password = model.Password,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Birthday = model.Birthday,
                    CreatedAt = DateTime.UtcNow
                };

                _dbContext.Clients?.Add(client);
                _dbContext.SaveChanges();

                HttpContext.Session.SetInt32("ClientId", client.Id);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult Login(LoginViewModel model)
        //{
        //    var client = _dbContext.Clients?.FirstOrDefault(c => c.Username == model.Username && c.Password == model.Password);

        //    if (client != null)
        //    {
        //        HttpContext.Session.SetString("ClientId", client.Id.ToString());
        //        ViewBag.userClient = client;
        //        return RedirectToAction("Index", "Home");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError("Username", "Invalid username or password.");
        //        return View(model);
        //    }
        //}

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            var client = _dbContext.Clients?.FirstOrDefault(c => c.Username == model.Username && c.Password == model.Password);

            if (client != null)
            {
                TempData["ClientId"] = client.Id;
                ViewBag.userClient = client;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("Username", "Invalid username or password.");
                return View(model);
            }
        }


        [HttpPost]
        public IActionResult Search(string manufacturer, string model, int? year, string color, decimal? minPrice, decimal? maxPrice)
        {
            var cars = _dbContext.Cars?.Where(c =>
                (manufacturer == null || c.Manufacturer == manufacturer) &&
                (model == null || c.Model == model) &&
                (!year.HasValue || c.Year == year.Value) &&
                (color == null || c.Color == color) &&
                (!minPrice.HasValue || c.RentalPricePerDay >= minPrice.Value) &&
                (!maxPrice.HasValue || c.RentalPricePerDay <= maxPrice.Value)).ToList();

            if (string.IsNullOrWhiteSpace(manufacturer) &&
                string.IsNullOrWhiteSpace(model) &&
                !year.HasValue &&
                string.IsNullOrWhiteSpace(color) &&
                !minPrice.HasValue &&
                !maxPrice.HasValue)
            {
                return View("NoResults"); // NoResults.cshtml to be created
            }

            return View(cars);
        }




        [HttpPost]
        public IActionResult Profile(ProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var client = ViewBag.userClient;
                {
                    model.Username = client.Username;
                    model.Email = client.Email;
                    model.FirstName = client.FirstName;
                    model.LastName = client.LastName;
                    model.Birthday = client.Birthday;
                    model.City = client.City;
                };

            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View();
        }

    }
}

CarRental/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

    <br />
    <div class="row">
        <div class="col-md-2">
            <button type="button" class="btn btn-primary btn-block mb-2" data-toggle="collapse" data-target="#carStock">See the entire car stock</button>
            <div class="collapse" id="carStock">
                <div class="card card-body">
                    <a href="/html/Car.html" class="btn btn-secondary btn-block mb-2">SUV</a>
                    <a href="/html/Car.html" class="btn btn-secondary btn-block mb-2">Hatchback</a>
                    <a href="/html/Car.html" class="btn btn-secondary btn-block mb-2">Sedan</a>
                </div>
            </div>
            <button type="button" class="btn btn-primary btn-block mb-2" data-toggle="collapse" data-target="#filterSearch">Filter or Search a certain car</button>
            <div class="collapse" id="filterSearch">
                <div class="card card-body">
                    <form method="post" action="/Home/Search">
                        <div class="form-group">
                            <label for="manufacturer">Manufacturer:</label>
                            <input type="text" class="form-control" id="manufacturer" name="manufacturer">
                        </div>
                        <div class="form-group">
                            <label for="model">Model:</label>
                            <input type="text" class="form-control" id="model" name="model">
                        </div>
                        <div class="form-group">
                            <label for="year">Year:</label>
                            <input type="text" class="form-control" id="year" name="year">
                        </div>
                        <div class="form-group">
                            <label for="color">Color:</label>
                            <select class="form-control" id="color" name="color">
                                <option value="">Select a color</option>
                                <option value="blue">Blue</option>
                                <option value="black">Black</option>
                                <option value="red">Red</option>
                                <option value="white">White</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="price">Price Range:</label>
                            <div class="row">
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="minPrice" name="minPrice" placeholder="Minimum Price">
                                </div>
                                <div class="col-sm-6">
                                    <label type="text" class="form-control" id="maxPrice" name="maxPrice" placeholder="Maximum Price">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <select class="form-control" id="minPriceDropdown" name="minPriceDropdown">
                                        <option value="">Select Min Price</option>
                                        <option value="100">100 lei</option>
                                        <option value="200">200 lei</option>
                                        <option value="300">300 lei</option>
                                        <option value="400">400 lei</option>
                                    </select>
                                </div>
                                <div class="col-sm-6">
                                    <select class="form-control" id="maxPriceDropdown" name="maxPriceDropdown">
                                        <option value="">Select Max Price</option>
                                        <option value="100">100 lei</option>
                                        <option value="200">200 lei</option>
                                        <option value="300">300 lei</option>
                                        <option value="400">400 lei</option>
                                        <option value="500">500 lei</option>
                                        <option value="600">600 lei</option>
                                        <option value="700">700 lei</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Apply Filters</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="carousel slide" data-ride="carousel" id="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel" data-slide-to="1"></li>
                    <li data-target="#carousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://via.placeholder.com/800x400?text=Our+clients+favorite+car" class="d-block w-100" alt="Our clients favorite car">
                    </div>
                    <div class="carousel-item">
                        <img src="https://via.placeholder.com/800x400?text=Most+popular+SUV" class="d-block w-100" alt="Most popular SUV">
                    </div>
                    <div class="carousel-item">
                        <img src="https://via.placeholder.com/800x400?text=Most+popular+category" class="d-block w-100" alt="Most popular category">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card">
                <div class="card-header">
                    <h5>News</h5>
                </div>
                <div class="card-body">
                    <p>Stay up-to-date with our latest news and updates.</p>
                    <a href="#" class="btn btn-primary">Read more</a>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-header">
                    <h5>Promotional Campaigns</h5>
                </div>
                <div class="card-body">
                    <p>Take advantage of our special promotions and discounts.</p>
                    <a href="#" class="btn btn-primary">Learn more</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

CarRental/Views/Home/Login.cshtml
@{
    Layout = null;
}
@model CarRental.ViewModels.LoginViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <link rel="stylesheet" href="../css/Login.css" />
</head>
<body>
    <div class="container">
        <form class="form" method="post" asp-controller="Home" asp-action="Login">
            <h1 class="form-title">Login</h1>
            <div class="form-group">
                <label asp-for="Username" class="form-label"></label>
                <input asp-for="Username" class="form-control" required>
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" type="password" required>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
            <href>Forgot your password?</href>
            <div class="form-group">
                <span class="error-message" id="error-message"></span>
            </div>
        </form>
    </div>
    <br />
    <br />
    <br />
</body>
</html>

CarRental/Views/Home/Profile.cshtml
@model CarRental.ViewModels.ProfileViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile Page</title>
    <link rel="stylesheet" href="../css/Profile.css">
</head>
<body>
    <br />
    <br />
    <div class="container">
        <div class="profile-header">
            <img src="user-icon.png" alt="User Icon" class="user-icon">
            <button class="change-icon-btn">Change Icon</button>
        </div>
        <div class="profile-content">
            <h2>Profile</h2>
            <div class="profile-field">
                <h3>Username:</h3>
                @if (Model != null)
                {
                    <p>@Model.Username</p>
                }
                <button class="modify-btn">Modify</button>
            </div>
            <div class="profile-field">
                <h3>Email:</h3>
                @if (Model != null)
                {
                    <p>@Model.Email</p>
                }
                <button class="modify-btn">Modify</button>
            </div>
            <div class="profile-field">
                <h3>Name:</h3>
                @if (Model != null)
                {
                    <p>@Model.FirstName @Model.LastName</p>
                }
                <button class="modify-btn">Modify</button>
            </div>
            <div class="profile-field">
                <h3>City:</h3>
                @if (Model != null)
                {
                    <p>@Model.City</p>
                }
                <button class="modify-btn">Modify</button>
            </div>
            <div class="profile-field">
                <h3>Birthday:</h3>
                @if (Model != null)
                {
                    <p>@Model.Birthday</p>
                }
                <button class="modify-btn">Modify</button>
            </div>
            <div class="password-link">
                <a href="#">Do you want to change your password?</a>
            </div>
        </div>
    </div>
    <br />
    <br />
</body>
</html>

CarRental/Views/Home/Registration.cshtml
@{
    Layout = null;
}
@model CarRental.ViewModels.RegistrationViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    <link rel="stylesheet" href="../css/Registration.css" />
</head>
<body>
    <div class="container">
        <form class="form" method="post" asp-controller="Home" asp-action="Registration">
            <h1 class="form-title">Registration</h1>
            <div class="form-group">
                <label asp-for="Username" class="form-label"></label>
                <input asp-for="Username" class="form-control" required>
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" type="password" required>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="form-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" type="password" required>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" type="email" required>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmEmail" class="form-label"></label>
                <input asp-for="ConfirmEmail" class="form-control" type="email" required>
                <span asp-validation-for="ConfirmEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="firstName" class="form-label">First Name</label>
                <input asp-for="FirstName" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="lastName" class="form-label">Last Name</label>
                <input asp-for="LastName" class="form-control" required>
            </div>

            <div class="form-group">
                <label asp-for="Birthday" class="form-label"></label>
                <input asp-for="Birthday" class="form-control" type="date" required>
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Register</button>
            </div>
            <div class="form-group">
                <span class="error-message" id="error-message"></span>
            </div>
        </form>
    </div>
    <script src="script.js"></script>
    <br />
    <br />
    <br />
    <br />
    <br />
</body>
</html>

CarRental/Views/Home/Search.cshtml
@model List<Car>
<link rel="stylesheet" href="../css/Search.css" />

<h1>Search Results</h1>

@if (Model.Count == 0)
{
    <p>No cars found.</p>
}
else
{
    <table>
        <thead>
            <tr>
                <th>Manufacturer</th>
                <th>Model</th>
                <th>Year</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model)
            {
                <tr>
                    <td>@car.Manufacturer</td>
                    <td>@car.Model</td>
                    <td>@car.Year</td>
                    <td><a href="@Url.Action("Details", "Cars", new { id = car.Id })">View details</a></td>
                </tr>
            }
        </tbody>
    </table>
}